### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by willbarkoff** [ULTIMATHEXERS/DaltonTab#1]
@thatoddmailbox @medensqui Do we really want to use bootstrap?

**Comment by medensqui** [comment]
@nywillb Yes

**Comment by medensqui** [comment]
@nywillb Studer found a bootstrappy version of the thing you were looking for

**Comment by thatoddmailbox** [comment]
@nywillb http://getbootstrap.com/javascript/#scrollspy

**Comment by willbarkoff** [comment]
@thatoddmailbox Perfect! This theme looks nice (with a litttle modification): http://ironsummitmedia.github.io/startbootstrap-stylish-portfolio/)

**Comment by medensqui** [comment]
@nywillb @thatoddmailbox Closing b/c I think it's done
