### ISSUE TITLE
Island Photo

### ISSUE THREAD

**Issue by willbarkoff** [ULTIMATHEXERS/DaltonTab#12]
Sometimes an island appears instead of the photo of the day.

**Comment by thatoddmailbox** [comment]
@nywillb that's...weird. Have you found anything in common with the times the island appears?

**Comment by willbarkoff** [comment]
@thatoddmailbox Got a picture!
![screen shot 2016-02-11 at 9 58 08 pm](https://cloud.githubusercontent.com/assets/10969136/12997769/a14d11a6-d10a-11e5-96f0-7c0aad6018e0.png)

**Comment by willbarkoff** [comment]
@thatoddmailbox Maybe it is some catcheing thing

**Comment by thatoddmailbox** [comment]
@nywillb does the island go away and come back? if so, that would be a __weird__ caching issue

**Comment by thatoddmailbox** [comment]
@nywillb My DaltonTab is getting a wintery snowy tree thing right now...

**Comment by thatoddmailbox** [comment]
@nywillb I've added some debugging code to the latest version of DaltonTab, 0.3.0 (it's live in the Web Store now). Next time you see the island, please open the console and look for a line that says `=== START BING IMAGE STUFF ===`. You'll see something called `Object`. **Fully expand the object and screenshot it.** (it's OK if you have to take multiple screenshots) Here is an example:

![screen shot 2016-02-19 at 1 56 41 pm](https://cloud.githubusercontent.com/assets/1904587/13185794/f6cfdefe-d710-11e5-981a-f6ccf02e6615.png)

**Comment by thatoddmailbox** [comment]
The image source has changed, so this should not happen anymore.
