### ISSUE TITLE
PlanHub Tags

### ISSUE THREAD

**Issue by amazansky** [ULTIMATHEXERS/DaltonTab#15]
Tags that are coded into PlanHub but not DaltonTab still appear as "tag not defined" pinkish color...
Example: `Prez`
CSS Hexing?

**Comment by thatoddmailbox** [comment]
@RobotXLabs we could just add them in, but it would be nice if it could get the latest tags __somehow__. Maybe including `utils.js`? Hmm...

**Comment by thatoddmailbox** [comment]
This was actually fixed a while ago, in 81dd1e4.
