### ISSUE TITLE
Update to new MyHomeworkSpace API

### ISSUE THREAD

**Issue by thatoddmailbox** [ULTIMATHEXERS/DaltonTab#16]
See title.

We have to do this in a way that would allow some overlap. (we would release a DaltonTab update before the migration that would work both before and after migration.) Maybe have two different JavaScript files, and it could somehow check if it's migrated and switch between the two?

**Comment by willbarkoff** [comment]
Maybe have a set date of migration and if it is set after that date, but
then if we run into migration issues.

**Comment by thatoddmailbox** [comment]
Already done.
