### ISSUE TITLE
Less scrolly interface

### ISSUE THREAD

**Issue by thatoddmailbox** [ULTIMATHEXERS/DaltonTab#19]
A common complaint from the surveys was that it was annoying to scroll down a lot, maybe make the sections smaller or have an alternative layout?

**Comment by willbarkoff** [comment]
Arrow keys?

**Comment by thatoddmailbox** [comment]
@nywillb Arrow keys?

**Comment by willbarkoff** [comment]
Nobody has complained about this in awhile, closing as wontfix for now.
