### ISSUE TITLE
Productivity

### ISSUE THREAD

**Issue by willbarkoff** [ULTIMATHEXERS/DaltonTab#2]
@thatoddmailbox @medensqui @c20et WE NEED TO START CODING! WE HAVE GONE A DAY AND GOTTEN NOTHING DONE.

**Comment by medensqui** [comment]
@nywillb I KNOW IM TRYING TO POKE STUDER. I INSTALLED BOOTSTRAP I HAVE DONE SOMETHING. U AND EESHAN ALSO HAVE TO CODE!!!!!! YARG

**Comment by willbarkoff** [comment]
@medensqui I HAVE CODED

**Comment by willbarkoff** [comment]
@thatoddmailbox I heard you dont know what to work on:
- [x] scrollspy
- [ ] API intagration
- [ ] Styling
- [ ] NewLab Approval

**Comment by medensqui** [comment]
@nywillb WERE CODING AND WE'RE ACTUALLY ALMOST DONE SCROLLSPY WAS THE BULK OF IT WE CAN'T GET IT APPROVED OVER NIGHT SO WE HAVE TO TEST USING LUCIUS
