### ISSUE TITLE
Inspirational quotes

### ISSUE THREAD

**Issue by thatoddmailbox** [ULTIMATHEXERS/DaltonTab#25]
Suggested by @medensqui. Not sure where we will find those, so I'm making that @medensqui's problem by assigning him to this issue. (ha)

**Comment by willbarkoff** [comment]
We've gotten no response from @medensqui, and it doesn't seem like anyone else wants this, so I'm closing it is wontfix - if anyone else wants this, feel free to reopen the issue.
