### ISSUE TITLE
Colors/Background

### ISSUE THREAD

**Issue by willbarkoff** [ULTIMATHEXERS/DaltonTab#3]
@thatoddmailbox @medensqui @c20et we need to decide what to do with backgrounds. I was thinking bing image of the day for the time section, but regular colors for everything else.

**Comment by thatoddmailbox** [comment]
@nywillb is there an API to get the current image?

**Comment by thatoddmailbox** [comment]
@nywillb Actually, never mind, I found it. http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US
