### ISSUE TITLE
Parallax Issues

### ISSUE THREAD

**Issue by willbarkoff** [ULTIMATHEXERS/DaltonTab#6]
We need to
- [ ] find a new parallax library (Easier, worse)
- [x] modify the existing library (Harder, better)

**Comment by willweinstein** [comment]
@nywillb is it that white thingy thats wrong with the parallax or is it something new?

**Comment by willweinstein** [comment]
@nywillb if its the white area, we can't fix that... the picture is the size of the windows so if the picture scrolls up, any parallax effect would leave a white area. Solutions may include: just having the background still and the stuff scroll without a parallax effect or use daily images from a site that has longer images

**Comment by thatoddmailbox** [comment]
@willweinstein or stretching/tiling the image some more

**Comment by willbarkoff** [comment]
@willweinstein @thatoddmailbox: Something Really weird just happened. Pay attention to the paralax when the gray bar comes up.
[Video](https://drive.google.com/a/dalton.org/file/d/0B95e9XN4UEZ8bzVnR0FfeXF0bWc/view?usp=sharing) (Sorry, but if you do not attend The Dalton School, you cannot watch the video. :frowning:).

**Comment by thatoddmailbox** [comment]
@nywillb did it happen after a reload? Also, you look to be using an old version of DaltonTab. Upgrade it (from the Chrome extensions page if from the webstore, or from the GitHub app if using developer version).

**Comment by willbarkoff** [comment]
@thatoddmailbox @willweinstein: I found another paralax library with more features: https://github.com/Prinzhorn/skrollr

**Comment by willbarkoff** [comment]
```
$(document).ready(function() {
    $(window).trigger('resize')
}};
```

Will that work?

**Comment by thatoddmailbox** [comment]
@nywillb we already tried that, twice
https://github.com/ULTIMATHEXERS/DaltonTab/blob/master/js/main.js#L113

https://github.com/ULTIMATHEXERS/DaltonTab/blob/master/js/main.js#L231

**Comment by thatoddmailbox** [comment]
This doesn't really matter anymore because it's no longer using a parallax effect.
