### ISSUE TITLE
Feature: Weather

### ISSUE THREAD

**Issue by amazansky** [ULTIMATHEXERS/DaltonTab#9]
How about weather on the new tab?

**Comment by thatoddmailbox** [comment]
We could reuse [the code from CoursesPlus](https://github.com/CoursesPlus/CoursesPlus/blob/master/js/weatherdisplay.js) for weather here.

**Comment by amazansky** [comment]
Cool!

**Comment by thatoddmailbox** [comment]
Done in 59c84cf, a day after this issue's birthday.
